postgresqlImage:
  tag: 14.2.0-debian-10-r60
postgresql:
  replicaCount: %d
  password: %s
  pgHbaTrustAll: true
persistence:
  size: %s
tls:
  enabled: true
  certificatesSecret: "postgresql-tls"
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: %s
  type: LoadBalancer
pgpoolImage:
  tag: 4.3.1-debian-10-r49
pgpool:
  customUsersSecret: pool-passwd
  tls:
    enabled: true
    certificatesSecret: "postgresql-tls"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    # certCAFilename: "ca.crt"
